<?php
/**
 * пути при входе в систему администрирования
 */
set_include_path(
		get_include_path().PATH_SEPARATOR
		.ROOT.DIRECTORY_SEPARATOR.'admin'.PATH_SEPARATOR
		.ROOT.DIRECTORY_SEPARATOR.'admin'.DIRECTORY_SEPARATOR.'core'.PATH_SEPARATOR
		.ROOT.DIRECTORY_SEPARATOR.'admin'.DIRECTORY_SEPARATOR.'modules'.PATH_SEPARATOR
		.ROOT.DIRECTORY_SEPARATOR.'admin'.DIRECTORY_SEPARATOR.'includes'.PATH_SEPARATOR
		.ROOT.DIRECTORY_SEPARATOR.'admin'.DIRECTORY_SEPARATOR.'blocks'.PATH_SEPARATOR
		.ROOT.DIRECTORY_SEPARATOR.'admin'.DIRECTORY_SEPARATOR.'classes'.PATH_SEPARATOR
);